import type {
  NotificationEvent,
  NotificationRow,
} from "@shared/schema";

export const notificationUsers = {
  admin: {
    id: "usr-301",
    name: "Meera Iyer",
    avatarUrl: "https://i.pravatar.cc/120?img=24",
    role: "ADMIN",
    orgId: "org-acme",
  },
  moderator: {
    id: "usr-202",
    name: "Kabir Rao",
    avatarUrl: "https://i.pravatar.cc/120?img=52",
    role: "MODERATOR",
    orgId: "org-filflo",
  },
  user: {
    id: "usr-101",
    name: "Aarav Mehta",
    avatarUrl: "https://i.pravatar.cc/120?img=11",
    role: "USER",
    orgId: "org-acme",
  },
} satisfies Record<string, NotificationEvent["actor"]>;

export const notificationRows: NotificationRow[] = [
  {
    id: "ntf-1001",
    type: "ticket_invitation",
    tier: "action_required",
    state: "inbox",
    ticket: {
      id: "TCK-1001",
      subject: "Unable to sync vendor invoices",
      orgId: "org-acme",
      orgName: "Acme Finance",
    },
    latestEvent: {
      description: "Meera invited you to review the invoice sync issue.",
      actor: notificationUsers.admin,
      at: "2026-05-02T06:15:00.000Z",
    },
    eventCount: 3,
    invitationId: "inv-1001",
    invitationStatus: "pending",
  },
  {
    id: "ntf-1002",
    type: "message_activity",
    tier: "status_update",
    state: "inbox",
    ticket: {
      id: "TCK-1002",
      subject: "Approval queue shows duplicate items",
      orgId: "org-nova",
      orgName: "Nova Retail",
    },
    latestEvent: {
      description: "Kabir added a reproduction note on the ticket thread.",
      actor: notificationUsers.moderator,
      at: "2026-05-02T05:30:00.000Z",
    },
    eventCount: 5,
  },
  {
    id: "ntf-1003",
    type: "ticket_assigned",
    tier: "action_required",
    state: "read",
    ticket: {
      id: "TCK-1003",
      subject: "Exported audit report missing comments",
      orgId: "org-acme",
      orgName: "Acme Finance",
    },
    latestEvent: {
      description: "Aarav assigned the audit report ticket to you.",
      actor: notificationUsers.user,
      at: "2026-05-01T12:20:00.000Z",
    },
    eventCount: 2,
  },
  {
    id: "ntf-1004",
    type: "ticket_resolved",
    tier: "fyi",
    state: "done",
    ticket: {
      id: "TCK-1001",
      subject: "Unable to sync vendor invoices",
      orgId: "org-acme",
      orgName: "Acme Finance",
    },
    latestEvent: {
      description: "Invoice sync was resolved and is ready for verification.",
      actor: notificationUsers.moderator,
      at: "2026-05-01T10:05:00.000Z",
    },
    eventCount: 4,
  },
  {
    id: "ntf-1005",
    type: "ticket_assigned",
    tier: "action_required",
    state: "inbox",
    ticket: {
      id: "a3f7c012",
      subject: "Fix auth token refresh on session timeout",
      orgId: "org-nova",
      orgName: "Nova Retail",
    },
    latestEvent: {
      description: "Kabir assigned the session timeout ticket to you.",
      actor: notificationUsers.moderator,
      at: "2026-05-02T13:14:00.000Z",
    },
    eventCount: 1,
  },
  {
    id: "ntf-1006",
    type: "review_requested",
    tier: "action_required",
    state: "inbox",
    ticket: {
      id: "b88a41de",
      subject: "Update rate limiter config for /api/v2/*",
      orgId: "org-acme",
      orgName: "Acme Finance",
    },
    latestEvent: {
      description: "Meera requested your review before rollout.",
      actor: notificationUsers.admin,
      at: "2026-05-02T13:05:00.000Z",
    },
    eventCount: 2,
  },
  {
    id: "ntf-1007",
    type: "message_activity",
    tier: "fyi",
    state: "inbox",
    ticket: {
      id: "cc21af09",
      subject: "Investigate webhook retries after Stripe outage",
      orgId: "org-filflo",
      orgName: "Filflo Core",
    },
    latestEvent: {
      description: "Aarav added three new debugging notes.",
      actor: notificationUsers.user,
      at: "2026-05-02T12:44:00.000Z",
    },
    eventCount: 4,
  },
  {
    id: "ntf-1008",
    type: "ticket_resolved",
    tier: "status_update",
    state: "inbox",
    ticket: {
      id: "d13e9b70",
      subject: "Resolve incorrect SLA badge on escalated tickets",
      orgId: "org-nova",
      orgName: "Nova Retail",
    },
    latestEvent: {
      description: "The SLA badge fix was resolved and awaits verification.",
      actor: notificationUsers.moderator,
      at: "2026-05-02T11:36:00.000Z",
    },
    eventCount: 1,
  },
  {
    id: "ntf-1009",
    type: "message_activity",
    tier: "fyi",
    state: "inbox",
    ticket: {
      id: "ef64aa18",
      subject: "Add audit trail for organization role changes",
      orgId: "org-acme",
      orgName: "Acme Finance",
    },
    latestEvent: {
      description: "Meera posted the expected audit payload shape.",
      actor: notificationUsers.admin,
      at: "2026-05-02T10:12:00.000Z",
    },
    eventCount: 3,
  },
  {
    id: "ntf-1010",
    type: "ticket_assigned",
    tier: "action_required",
    state: "inbox",
    ticket: {
      id: "f5012b9c",
      subject: "Patch message composer losing drafts on route change",
      orgId: "org-filflo",
      orgName: "Filflo Core",
    },
    latestEvent: {
      description: "Kabir assigned the draft persistence issue to you.",
      actor: notificationUsers.moderator,
      at: "2026-05-02T08:25:00.000Z",
    },
    eventCount: 1,
  },
  {
    id: "ntf-1011",
    type: "review_requested",
    tier: "action_required",
    state: "read",
    ticket: {
      id: "102ab8ce",
      subject: "Review query cache invalidation for notifications",
      orgId: "org-filflo",
      orgName: "Filflo Core",
    },
    latestEvent: {
      description: "Meera requested review on the notification cache patch.",
      actor: notificationUsers.admin,
      at: "2026-05-01T16:42:00.000Z",
    },
    eventCount: 2,
  },
  {
    id: "ntf-1012",
    type: "ticket_closed",
    tier: "status_update",
    state: "read",
    ticket: {
      id: "21d4ce90",
      subject: "Close stale sandbox provisioning incident",
      orgId: "org-nova",
      orgName: "Nova Retail",
    },
    latestEvent: {
      description: "Sandbox provisioning incident was closed.",
      actor: notificationUsers.moderator,
      at: "2026-05-01T09:55:00.000Z",
    },
    eventCount: 1,
  },
  {
    id: "ntf-1013",
    type: "message_activity",
    tier: "fyi",
    state: "read",
    ticket: {
      id: "349bd01f",
      subject: "Clarify billing export column naming",
      orgId: "org-acme",
      orgName: "Acme Finance",
    },
    latestEvent: {
      description: "Aarav replied with the finance team's preferred labels.",
      actor: notificationUsers.user,
      at: "2026-04-30T14:10:00.000Z",
    },
    eventCount: 2,
  },
  {
    id: "ntf-1014",
    type: "ticket_resolved",
    tier: "status_update",
    state: "read",
    ticket: {
      id: "45ae10c2",
      subject: "Fix CSV import hanging on blank final rows",
      orgId: "org-acme",
      orgName: "Acme Finance",
    },
    latestEvent: {
      description: "CSV import fix was resolved after parser guards landed.",
      actor: notificationUsers.admin,
      at: "2026-04-30T08:18:00.000Z",
    },
    eventCount: 1,
  },
  {
    id: "ntf-1015",
    type: "message_activity",
    tier: "fyi",
    state: "done",
    ticket: {
      id: "56f01acd",
      subject: "Document retry behavior for failed uploads",
      orgId: "org-filflo",
      orgName: "Filflo Core",
    },
    latestEvent: {
      description: "Kabir confirmed the docs now match production behavior.",
      actor: notificationUsers.moderator,
      at: "2026-04-29T17:25:00.000Z",
    },
    eventCount: 1,
  },
  {
    id: "ntf-1016",
    type: "new_ticket_in_org",
    tier: "status_update",
    state: "done",
    ticket: {
      id: "6780fa3b",
      subject: "Add org-level toggle for digest emails",
      orgId: "org-nova",
      orgName: "Nova Retail",
    },
    latestEvent: {
      description: "A new ticket was opened in Nova Retail.",
      actor: notificationUsers.user,
      at: "2026-04-28T15:31:00.000Z",
    },
    eventCount: 1,
  },
  {
    id: "ntf-1017",
    type: "ticket_assigned",
    tier: "action_required",
    state: "read",
    ticket: {
      id: "789c12de",
      subject: "Investigate API 409s when accepting invitations",
      orgId: "org-acme",
      orgName: "Acme Finance",
    },
    latestEvent: {
      description: "Meera assigned the invitation conflict bug to you.",
      actor: notificationUsers.admin,
      at: "2026-04-27T12:09:00.000Z",
    },
    eventCount: 1,
  },
  {
    id: "ntf-1018",
    type: "message_activity",
    tier: "fyi",
    state: "inbox",
    ticket: {
      id: "8ab33c90",
      subject: "Tune search ranking for exact ticket IDs",
      orgId: "org-filflo",
      orgName: "Filflo Core",
    },
    latestEvent: {
      description: "Kabir shared before-and-after ranking examples.",
      actor: notificationUsers.moderator,
      at: "2026-04-27T08:44:00.000Z",
    },
    eventCount: 3,
  },
  {
    id: "ntf-1019",
    type: "ticket_closed",
    tier: "status_update",
    state: "done",
    ticket: {
      id: "9cdef201",
      subject: "Remove deprecated moderator permission flag",
      orgId: "org-filflo",
      orgName: "Filflo Core",
    },
    latestEvent: {
      description: "Deprecated permission flag cleanup was closed.",
      actor: notificationUsers.admin,
      at: "2026-04-25T11:22:00.000Z",
    },
    eventCount: 1,
  },
  {
    id: "ntf-1020",
    type: "message_activity",
    tier: "fyi",
    state: "done",
    ticket: {
      id: "aa014bfe",
      subject: "Add clearer copy for expired invite links",
      orgId: "org-nova",
      orgName: "Nova Retail",
    },
    latestEvent: {
      description: "Aarav approved the final expired invite copy.",
      actor: notificationUsers.user,
      at: "2026-04-24T10:04:00.000Z",
    },
    eventCount: 2,
  },
  {
    id: "ntf-1021",
    type: "message_activity",
    tier: "fyi",
    state: "read",
    ticket: {
      id: "bc72ef43",
      subject: "Trace slow websocket reconnect after laptop sleep",
      orgId: "org-filflo",
      orgName: "Filflo Core",
    },
    latestEvent: {
      description: "Meera attached a timeline from the reconnect test.",
      actor: notificationUsers.admin,
      at: "2026-04-23T18:48:00.000Z",
    },
    eventCount: 4,
  },
  {
    id: "ntf-1022",
    type: "ticket_resolved",
    tier: "status_update",
    state: "done",
    ticket: {
      id: "cd90a721",
      subject: "Resolve attachment preview failing for PDFs",
      orgId: "org-acme",
      orgName: "Acme Finance",
    },
    latestEvent: {
      description: "PDF attachment previews were resolved.",
      actor: notificationUsers.moderator,
      at: "2026-04-22T07:33:00.000Z",
    },
    eventCount: 1,
  },
  {
    id: "ntf-1023",
    type: "new_ticket_in_org",
    tier: "status_update",
    state: "read",
    ticket: {
      id: "de18fb44",
      subject: "Add webhook delivery metrics to org settings",
      orgId: "org-nova",
      orgName: "Nova Retail",
    },
    latestEvent: {
      description: "A new ticket was opened in Nova Retail.",
      actor: notificationUsers.user,
      at: "2026-04-21T13:19:00.000Z",
    },
    eventCount: 1,
  },
  {
    id: "ntf-1024",
    type: "message_activity",
    tier: "fyi",
    state: "done",
    ticket: {
      id: "e01c77ab",
      subject: "Check flaky notification count polling in Safari",
      orgId: "org-filflo",
      orgName: "Filflo Core",
    },
    latestEvent: {
      description: "Kabir confirmed Safari no longer double-polls.",
      actor: notificationUsers.moderator,
      at: "2026-04-20T16:11:00.000Z",
    },
    eventCount: 2,
  },
  {
    id: "ntf-1025",
    type: "review_requested",
    tier: "action_required",
    state: "done",
    ticket: {
      id: "f3a42c09",
      subject: "Review optimistic updates for bulk notification actions",
      orgId: "org-filflo",
      orgName: "Filflo Core",
    },
    latestEvent: {
      description: "Meera requested review on the bulk action mutation patch.",
      actor: notificationUsers.admin,
      at: "2026-04-19T09:26:00.000Z",
    },
    eventCount: 2,
  },
  {
    id: "ntf-1026",
    type: "message_activity",
    tier: "fyi",
    state: "read",
    ticket: {
      id: "01bc99ef",
      subject: "Normalize ticket search params before API calls",
      orgId: "org-acme",
      orgName: "Acme Finance",
    },
    latestEvent: {
      description: "Aarav posted the failing URL example.",
      actor: notificationUsers.user,
      at: "2026-04-18T14:37:00.000Z",
    },
    eventCount: 1,
  },
  {
    id: "ntf-1027",
    type: "ticket_closed",
    tier: "status_update",
    state: "done",
    ticket: {
      id: "12aa40bd",
      subject: "Close duplicate ticket from billing import retry",
      orgId: "org-acme",
      orgName: "Acme Finance",
    },
    latestEvent: {
      description: "Duplicate billing import ticket was closed.",
      actor: notificationUsers.admin,
      at: "2026-04-18T10:08:00.000Z",
    },
    eventCount: 1,
  },
  {
    id: "ntf-1028",
    type: "message_activity",
    tier: "fyi",
    state: "done",
    ticket: {
      id: "23dcb80a",
      subject: "Clarify escalation handoff when admin is offline",
      orgId: "org-nova",
      orgName: "Nova Retail",
    },
    latestEvent: {
      description: "Kabir summarized the agreed handoff rule.",
      actor: notificationUsers.moderator,
      at: "2026-04-17T08:21:00.000Z",
    },
    eventCount: 3,
  },
];

export const notificationEvents: Record<string, NotificationEvent[]> = {
  "ntf-1001": [
    {
      id: "evt-1001-1",
      type: "ticket_invitation",
      description: "Meera invited you to review the invoice sync issue.",
      actor: notificationUsers.admin,
      at: "2026-05-02T06:15:00.000Z",
    },
    {
      id: "evt-1001-2",
      type: "message_activity",
      description: "Kabir shared connector logs in the ticket thread.",
      actor: notificationUsers.moderator,
      at: "2026-05-02T06:05:00.000Z",
    },
  ],
  "ntf-1002": [
    {
      id: "evt-1002-1",
      type: "message_activity",
      description: "Kabir added a reproduction note on the ticket thread.",
      actor: notificationUsers.moderator,
      at: "2026-05-02T05:30:00.000Z",
    },
  ],
  "ntf-1006": [
    {
      id: "evt-1006-1",
      type: "review_requested",
      description: "Meera requested your review before rollout.",
      actor: notificationUsers.admin,
      at: "2026-05-02T13:05:00.000Z",
    },
    {
      id: "evt-1006-2",
      type: "message_activity",
      description: "Kabir added the proposed limiter window and burst size.",
      actor: notificationUsers.moderator,
      at: "2026-05-02T12:58:00.000Z",
    },
  ],
  "ntf-1007": [
    {
      id: "evt-1007-1",
      type: "message_activity",
      description: "Aarav added three new debugging notes.",
      actor: notificationUsers.user,
      at: "2026-05-02T12:44:00.000Z",
    },
    {
      id: "evt-1007-2",
      type: "message_activity",
      description: "Kabir linked the retry job traces.",
      actor: notificationUsers.moderator,
      at: "2026-05-02T12:31:00.000Z",
    },
    {
      id: "evt-1007-3",
      type: "message_activity",
      description: "Meera asked whether failed attempts are idempotent.",
      actor: notificationUsers.admin,
      at: "2026-05-02T12:08:00.000Z",
    },
  ],
  "ntf-1009": [
    {
      id: "evt-1009-1",
      type: "message_activity",
      description: "Meera posted the expected audit payload shape.",
      actor: notificationUsers.admin,
      at: "2026-05-02T10:12:00.000Z",
    },
    {
      id: "evt-1009-2",
      type: "message_activity",
      description: "Aarav confirmed compliance needs actor and target roles.",
      actor: notificationUsers.user,
      at: "2026-05-02T09:48:00.000Z",
    },
    {
      id: "evt-1009-3",
      type: "message_activity",
      description: "Kabir attached the current role-change controller path.",
      actor: notificationUsers.moderator,
      at: "2026-05-02T09:34:00.000Z",
    },
  ],
  "ntf-1018": [
    {
      id: "evt-1018-1",
      type: "message_activity",
      description: "Kabir shared before-and-after ranking examples.",
      actor: notificationUsers.moderator,
      at: "2026-04-27T08:44:00.000Z",
    },
    {
      id: "evt-1018-2",
      type: "message_activity",
      description: "Meera suggested exact ID matches should skip fuzzy scoring.",
      actor: notificationUsers.admin,
      at: "2026-04-27T08:12:00.000Z",
    },
    {
      id: "evt-1018-3",
      type: "message_activity",
      description: "Aarav provided a ticket ID that currently ranks second.",
      actor: notificationUsers.user,
      at: "2026-04-27T07:55:00.000Z",
    },
  ],
  "ntf-1021": [
    {
      id: "evt-1021-1",
      type: "message_activity",
      description: "Meera attached a timeline from the reconnect test.",
      actor: notificationUsers.admin,
      at: "2026-04-23T18:48:00.000Z",
    },
    {
      id: "evt-1021-2",
      type: "message_activity",
      description: "Kabir noted the stale socket closes after foregrounding.",
      actor: notificationUsers.moderator,
      at: "2026-04-23T18:22:00.000Z",
    },
    {
      id: "evt-1021-3",
      type: "message_activity",
      description: "Aarav reproduced the issue after two sleep cycles.",
      actor: notificationUsers.user,
      at: "2026-04-23T17:59:00.000Z",
    },
  ],
  "ntf-1028": [
    {
      id: "evt-1028-1",
      type: "message_activity",
      description: "Kabir summarized the agreed handoff rule.",
      actor: notificationUsers.moderator,
      at: "2026-04-17T08:21:00.000Z",
    },
    {
      id: "evt-1028-2",
      type: "message_activity",
      description: "Meera asked for escalation ownership to stay visible.",
      actor: notificationUsers.admin,
      at: "2026-04-17T07:54:00.000Z",
    },
    {
      id: "evt-1028-3",
      type: "message_activity",
      description: "Aarav confirmed the support team can follow the rule.",
      actor: notificationUsers.user,
      at: "2026-04-17T07:32:00.000Z",
    },
  ],
};
